project:
  type: website

website:
  title: "Kylie Linden"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto


